class ClickHouseServerIsNotHealthyError(Exception): ...


class MigrationDirectoryNotFoundError(Exception): ...


class InvalidMigrationError(Exception): ...


class MissingDatabaseUrlError(Exception): ...


class DatabaseNotFoundError(Exception): ...


class ChecksumMismatchError(Exception): ...


class MigrationParseError(ValueError): ...
